# Site settings
author: A. Lee Vargas
title: Ale's Blog
header-img: img/home-bg.png
email: leevargasale@gmail.com
copyright_name: A. Lee Vargas
description: > # this means to ignore newlines until "baseurl:"
  My blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alelee93

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
